version: '3'

services:
  redis:
    container_name: open-finance-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - samplenetwork

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      - samplenetwork

  postgres:
    container_name: open-finance-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: open-finance
      POSTGRES_PASSWORD: open-finance
      POSTGRES_DB: open-finance
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - samplenetwork

  app:
    container_name: open-finance-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - samplenetwork
    command: ['yarn', 'dev']

volumes:
  redis:
    driver: local
  postgres-data:
    driver: local

networks:
  samplenetwork:
    driver: bridge
